version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    command: [ "mongod", "--bind_ip_all", "--noauth" ] # Tắt xác thực
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH: "false" # Tắt xác thực trên Mongo Express

volumes:
  mongodb_data:
    driver: local
